version: '3.8'

services:
  factorial_microservice:
    build: .
    #image: factorial_microservice:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - FACTORIAL_CACHE_SIZE=100
    restart: on-failure
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
