spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: factorial_microservice
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics
  prometheus:
    metrics:
      export:
        enabled: true

app:
  factorial:
    max-value: ${FACTORIAL_CACHE_SIZE:100}

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
